apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-system
spec:
  version: 8.19.4
  http:
    tls:
      certificate:
        secretName: elasticsearch-http-certs

  transport:
    tls:
      certificate:
        secretName: elasticsearch-transport-certs

  nodeSets:
    - name: masters
      count: 3
      config:
        node.roles: ["master"]
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: true
        xpack.security.transport.ssl.verification_mode: certificate
        xpack.security.transport.ssl.client_authentication: required
        xpack.security.http.ssl.enabled: true
        xpack.security.http.ssl.client_authentication: optional
        node.store.allow_mmap: false
        action.auto_create_index: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi
            storageClassName: longhorn
      podTemplate:
        spec:
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: elasticsearch
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              resources:
                requests:
                  cpu: "2"
                  memory: 2Gi
                limits:
                  cpu: "4"
                  memory: 4Gi
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms1g -Xmx2g"

    - name: data
      count: 2
      config:
        node.roles: ["data", "ingest"]
        xpack.security.enabled: true
        xpack.security.transport.ssl.enabled: true
        xpack.security.transport.ssl.verification_mode: certificate
        xpack.security.transport.ssl.client_authentication: required
        xpack.security.http.ssl.enabled: true
        xpack.security.http.ssl.client_authentication: optional
        node.store.allow_mmap: false
        action.auto_create_index: true
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 30Gi
            storageClassName: longhorn
      podTemplate:
        spec:
          securityContext:
            fsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: elasticsearch
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              resources:
                requests:
                  cpu: "2"
                  memory: 4Gi
                limits:
                  cpu: "4"
                  memory: 8Gi
              env:
                - name: ES_JAVA_OPTS
                  value: "-Xms2g -Xmx4g"
