apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: "https://vault.bitwarden.com/api"
      identityURL: "https://identity.bitwarden.com/core/connect/token"
      bitwardenServerSDKURL: "https://vault.bitwarden.com/"
      organizationID: "80e526c7-f256-4a5d-885c-b36d00e5b7f1"
      projectID: "d32d487f-2d1f-41c6-b8ee-b3740068336a"
      auth:
        secretRef:
          credentials:
            name: bitwarden-credentials
            namespace: external-secrets
            key: token
