---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz-k8s-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  sources:
    - repoURL: https://charts.signoz.io
      chart: k8s-infra
      targetRevision: 0.15.0
      helm:
        valueFiles:
          - $values/k8s/observability/signoz-k8s-infra/values/values.yaml
    - repoURL: https://github.com/pressogh/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
