---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: quay.io/jetstack/charts
    chart: trust-manager
    targetRevision: v0.22.0
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
        app:
          trust:
            namespace: cert-manager
        secretTargets:
          enabled: true
          authorizedSecretsAll: true
  destination:
    server: https://kubernetes.default.svc
    namespace: trust-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
