apiVersion: gateway.networking.k8s.io/v1alhpa2
kind: TLSRoute
metadata:
  name: elasticsearch-route
  namespace: elastic-system
  annotations:
    gateway.cilium.io/backend-protocol: "https"
spec:
  parentRefs:
    - name: internal-gw
      namespace: gateway-internal
      sectionName: es-tls
  hostnames:
    - es.home.arpa
  rules:
    - backendRefs:
      - name: elasticsearch-es-http
        port: 9200
