apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: elasticsearch-tcproute
  namespace: elastic-system
spec:
  parentRefs:
    - name: internal-gw
      namespace: gateway-internal
  rules:
    - backendRefs:
      - name: elasticsearch
        port: 9200