apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: bitnami/elasticsearch
      targetRevision: "22.1.6"
      helm:
        valueFiles:
          - $values/k8s-manifests/apps/elasticsearch/values/values.yaml
    - repoURL: https://github.com/pressogh/homelab.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: elastic-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true