tap:
  auth:
    enabled: false
  packetCapture: af_packet
  mountBpf: false
  serviceMesh: false
  tls: false
  ingress:
    enabled: false
  release:
    namespace: kubeshark
  telemetry:
    enabled: false
  persistentStorage: false
  persistentStorageStatic: false
  persistentStoragePvcVolumeMode: Filesystem
  snapshots:
    local:
      storageClass: longhorn
      storageSize: 20Gi
  capture:
    raw:
      enabled: false
  misc:
    trafficSampleRate: 25
  ipv6: false
cloudLicenseEnabled: false
supportChatEnabled: false
