tap:
  auth:
    enabled: false
  ingress:
    enabled: false
  release:
    namespace: kubeshark
  telemetry:
    enabled: false
  persistentStorage: false
  persistentStorageStatic: false
  persistentStoragePvcVolumeMode: Filesystem
  snapshots:
    local:
      storageClass: longhorn
      storageSize: 20Gi
  ipv6: false
cloudLicenseEnabled: false
supportChatEnabled: false
