---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-target
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: longhorn-backup-target
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        AWS_ENDPOINTS: https://f0a29a113a941dc654be1996cd611f97.r2.cloudflarestorage.com
      mergePolicy: Merge
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: b3937ef7-1574-4a3f-8720-b4170025b138
        metadataPolicy: None
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: 3ab387aa-a009-4916-91a6-b4170025d823
        metadataPolicy: None
