---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark-cleanup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/pressogh/homelab.git
    targetRevision: main
    path: k8s/kubeshark-cleanup
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeshark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
