apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-auth
  namespace: external-secrets

---

apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-auth-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: external-secrets-auth
type: kubernetes.io/service-account-token

---

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: openbao-backend
spec:
  provider:
    vault:
      server: "https://openbao-active.openbao.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      caProvider:
        type: ConfigMap
        name: internal-ca-bundle
        namespace: openbao
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets-auth"
            namespace: "external-secrets"