apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-auth-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: external-secrets-auth
type: kubernetes.io/service-account-token