apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterissuers/letsencrypt-public.yaml
  - clusterissuers/internal-selfsigned.yaml
  - clusterissuers/internal-ca.yaml
  - certificates/internal-root-ca.yaml
