apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: database
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: all apps for database
  destinations:
    - name: in-cluster
      namespace: '*'
      server: https://kubernetes.default.svc
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources: {}
  sourceRepos:
    - https://github.com/pressogh/homelab.git
    - https://helm.elastic.co
