---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Infrastructure controllers and shared platform resources
  sourceRepos:
    - https://github.com/pressogh/homelab.git
    - https://charts.jetstack.io
    - quay.io/jetstack/charts
    - https://charts.external-secrets.io
    - https://github.com/external-secrets/external-secrets
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: trust-manager
      server: https://kubernetes.default.svc
    - namespace: kubeshark
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
