---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Observability platforms and telemetry collectors
  sourceRepos:
    - https://charts.signoz.io
    - https://github.com/pressogh/homelab.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: signoz
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
