---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: secret-management
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: >
    Secret management infrastructure including OpenBao and  External Secrets Operator

  destinations:
    - name: in-cluster
      namespace: openbao
      server: https://kubernetes.default.svc
    - name: in-cluster
      namespace: external-secrets
      server: https://kubernetes.default.svc
    - name: '*'
      namespace: argocd
      server: '*'
    - name: '*'
      namespace: openbao
      server: '*'
    - name: '*'
      namespace: external-secrets
      server: '*'
    - name: '*'
      namespace: '*'
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  orphanedResources: {}
  sourceRepos:
    - https://openbao.github.io/openbao-helm
    - https://charts.external-secrets.io
    - https://github.com/pressogh/homelab.git
