global:
  clusterName: talos-homelab
  storageClass: longhorn

signoz:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: /metrics
  ingress:
    enabled: false
  service:
    type: ClusterIP
  persistence:
    enabled: true
    size: 2Gi
  env:
    signoz_alertmanager_signoz_external__url: https://signoz.home.arpa

clickhouse:
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9363"
    prometheus.io/path: /metrics
  persistence:
    enabled: true
    size: 50Gi
  layout:
    shardsCount: 1
    replicasCount: 1
  resources:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      memory: 3Gi
  zookeeper:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9141"
      prometheus.io/path: /metrics
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 768Mi
      limits:
        memory: 768Mi
  clickhouseOperator:
    podAnnotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8888"


otelCollector:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 512Mi
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8888"
  service:
    type: ClusterIP
