---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signoz
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: signoz-clickhouse-operator
      jsonPointers:
        - /spec/template/spec/containers/0/resources
        - /spec/template/spec/containers/1/resources
        - /spec/template/spec/dnsPolicy
        - /spec/template/spec/restartPolicy
        - /spec/template/spec/schedulerName
        - /spec/template/spec/serviceAccount
        - /spec/template/spec/terminationGracePeriodSeconds
    - group: apps
      kind: StatefulSet
      name: signoz
      jsonPointers:
        - /spec/template/spec/dnsPolicy
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/template/spec/restartPolicy
        - /spec/template/spec/schedulerName
        - /spec/template/spec/serviceAccount
        - /spec/template/spec/terminationGracePeriodSeconds
    - group: apps
      kind: StatefulSet
      name: signoz-zookeeper
      jsonPointers:
        - /spec/template/spec/dnsPolicy
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/template/spec/restartPolicy
        - /spec/template/spec/schedulerName
        - /spec/template/spec/serviceAccount
        - /spec/template/spec/terminationGracePeriodSeconds
  sources:
    - repoURL: https://charts.signoz.io
      chart: signoz
      targetRevision: 0.126.1
      helm:
        valueFiles:
          - $values/k8s/observability/signoz/values/values.yaml
    - repoURL: https://github.com/pressogh/homelab.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/pressogh/homelab.git
      targetRevision: main
      path: k8s/observability/signoz
  destination:
    server: https://kubernetes.default.svc
    namespace: signoz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        expose: internal
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: baseline
        pod-security.kubernetes.io/warn-version: latest
        pod-security.kubernetes.io/audit: baseline
        pod-security.kubernetes.io/audit-version: latest
