---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: secrets
  sources:
    - repoURL: https://charts.external-secrets.io
      chart: external-secrets
      targetRevision: 0.20.2
      helm:
        valueFiles:
          - $values/k8s/external-secrets/values/values.yaml
    - repoURL: https://github.com/pressogh/homelab.git
      targetRevision: main
      ref: values
      path: k8s/external-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        "pod-security.kubernetes.io/enforce": restricted
        "pod-security.kubernetes.io/enforce-version": latest
        "pod-security.kubernetes.io/warn": restricted
        "pod-security.kubernetes.io/warn-version": latest
        "pod-security.kubernetes.io/audit": restricted
        "pod-security.kubernetes.io/audit-version": latest
