---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.20.0
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
        global:
          leaderElection:
            namespace: cert-manager
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
        webhook:
          timeoutSeconds: 30
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        trust.cert-manager.io/inject: "true"
        pod-security.kubernetes.io/enforce: privileged
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
