---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager-csi-driver
    targetRevision: v0.13.0
    helm:
      releaseName: cert-manager-csi-driver
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
