apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: "fecccd3f-0c8b-4fa4-8927-b41600188c5a"
        metadataPolicy: None
