apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openbao-tls
  namespace: openbao
spec:
  secretName: openbao-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
      - Homelab
  commonName: openbao.openbao.svc.cluster.local
  dnsNames:
    - openbao
    - openbao-active
    - openbao-standby
    - openbao.openbao
    - openbao.openbao.svc
    - openbao.openbao.svc.cluster.local
    - openbao-active.openbao.svc.cluster.local
    - openbao-standby.openbao.svc.cluster.local
    - "*.openbao-internal"
    - "*.openbao-internal.openbao.svc.cluster.local"
  ipAddresses:
    - 127.0.0.1
    - "::1"
  usages:
    - server auth
    - client auth
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
    group: cert-manager.io
