---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-public
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: networking
  source:
    repoURL: https://github.com/pressogh/homelab.git
    targetRevision: main
    path: k8s/gateway/gateway-public
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-public
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    managedNamespaceMetadata:
      labels:
        expose: public
        trust.cert-manager.io/inject: "true"
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
